# AppProject for the multi-cluster hub model example.
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: multicluster-hub
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Deploy demo workloads from the hub Argo CD instance to spoke clusters
  sourceRepos:
    - https://github.com/awaismansha-00/gitops-with-argocd.git
  destinations:
    - server: '*'
      namespace: qa
    - server: '*'
      namespace: prod
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ''
      kind: Service
    - group: ''
      kind: ConfigMap
